AWS:
  Region: eu-central-1
Server:
  Host: 0.0.0.0
  Port: 8080
DynamoDB:
  Region: eu-central-1
  TableName: dynamo-db-task-1
  PrimaryPartitionKey: recordId
Redis:
  Host: redis-rep-group-task-1-0001-001.4uet7s.0001.euc1.cache.amazonaws.com
  Port: 6379
DB:
  Host: database-1.c2empzdo10xn.eu-central-1.rds.amazonaws.com
  Port: 3306
  User: admin
  Pass: Aa123456
  DBName: db01
  Table: testweb53